import Navbar from './components/Navbar';
import './globals.css'

// Importing font
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});


export const metadata = {
  title: "TSMCode - Learning Never Stops.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`}>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
